version: '3'
services:
  redis-shopping:
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6380:6379"
    volumes:
      - ./redis_data:/data

  mysql-shopping:
    image: mysql:latest
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: java_spring_shopping
    expose:
      - "3306"
    ports:
      - "3308:3306"

  my-app:
    image: my-app:test
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - redis-shopping
      - mysql-shopping